---
title: "Indicator Progress Tracker"
output: github_document
---

+----------------------------------------------+----------------------------------------------------------------------------+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------------+--------------+------+
| Indicator                                    | Dataset used                                                               | Function/file name               | Task                                                                                                                                                                                                                                                                                                         | Charged to: | In progress | Needs review | Done |
+----------------------------------------------+----------------------------------------------------------------------------+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------------+--------------+------+
| Heat index                                   |                                                                            |                                  |                                                                                                                                                                                                                                                                                                              | Caitlin     |             |              |      |
+----------------------------------------------+----------------------------------------------------------------------------+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------------+--------------+------+
| Canopy cover                                 |                                                                            |                                  |                                                                                                                                                                                                                                                                                                              | Caitlin     |             |              |      |
+----------------------------------------------+----------------------------------------------------------------------------+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------------+--------------+------+
| Wildfire risk                                | USDA/USFS (CO Enviroscreen)                                                | wildfire_risk.R                  | Mean wildfire hazard potential within prison boundary + 1km buffer                                                                                                                                                                                                                                           | Devin       | X           | X            |      |
+----------------------------------------------+----------------------------------------------------------------------------+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------------+--------------+------+
| Flood risk                                   | FEMA                                                                       |                                  | Percentage of each prison boundary + 1km buffer where there is at least a one percent chance of flooding annually                                                                                                                                                                                            | Caitlin     | X           |              |      |
+----------------------------------------------+----------------------------------------------------------------------------+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------------+--------------+------+
| Ozone                                        |                                                                            |                                  |                                                                                                                                                                                                                                                                                                              | Caitlin     |             |              |      |
+----------------------------------------------+----------------------------------------------------------------------------+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------------+--------------+------+
| PM 2.5                                       |                                                                            |                                  |                                                                                                                                                                                                                                                                                                              | Caitlin     |             |              |      |
+----------------------------------------------+----------------------------------------------------------------------------+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------------+--------------+------+
| Traffic volume and proximity                 |                                                                            |                                  | Count of vehicles (AADT, avg. annual daily traffic) at major roads within 500 meters, divided by distance in meters (EJ Screen)                                                                                                                                                                              | Caitlin     |             |              |      |
+----------------------------------------------+----------------------------------------------------------------------------+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------------+--------------+------+
| Pesticide use                                | SEDAC(PEST-CHEMGRIDS v1.01), CalEnviroScreen Table of volatile pesticides. | calcPesticides()                 | Total pounds of 132 selected active pesticide ingredients (filtered for hazard and volatility) used in production-agriculture per square mile, averaged over three years (2017 to 2019). (CA method: <https://oehha.ca.gov/media/downloads/calenviroscreen/report/calenviroscreen40reportf2021.pdf#page=79>) | Devin       | X           | X            |      |
|                                              |                                                                            |                                  |                                                                                                                                                                                                                                                                                                              |             |             |              |      |
|                                              |                                                                            | Files:                           |                                                                                                                                                                                                                                                                                                              |             |             |              |      |
|                                              |                                                                            |                                  |                                                                                                                                                                                                                                                                                                              |             |             |              |      |
|                                              |                                                                            | data/processed/pesticide_sedac,  |                                                                                                                                                                                                                                                                                                              |             |             |              |      |
|                                              |                                                                            |                                  |                                                                                                                                                                                                                                                                                                              |             |             |              |      |
|                                              |                                                                            | pesticide_sedac_2020.tif         |                                                                                                                                                                                                                                                                                                              |             |             |              |      |
+----------------------------------------------+----------------------------------------------------------------------------+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------------+--------------+------+
| Superfund and NPL proximity                  | EPA (Query: <https://cumulis.epa.gov/supercpad/cursites/srchsites.cfm>)    | Files:                           | Sum of listed and proposed NPL sites weighted by distance to prison boundary and type of NPL site (see CA EnviroScreen for weighting by site type: <https://oehha.ca.gov/media/downloads/calenviroscreen/report/calenviroscreen40reportf2021.pdf#page=108>)                                                  | Devin       | X           | X            |      |
|                                              |                                                                            |                                  |                                                                                                                                                                                                                                                                                                              |             |             |              |      |
|                                              |                                                                            | superfund_npl_active_2023ver.csv |                                                                                                                                                                                                                                                                                                              |             |             |              |      |
|                                              |                                                                            |                                  |                                                                                                                                                                                                                                                                                                              |             |             |              |      |
|                                              |                                                                            | Fun:                             |                                                                                                                                                                                                                                                                                                              |             |             |              |      |
|                                              |                                                                            |                                  |                                                                                                                                                                                                                                                                                                              |             |             |              |      |
|                                              |                                                                            | ArcGIS Pro geocoding             |                                                                                                                                                                                                                                                                                                              |             |             |              |      |
|                                              |                                                                            |                                  |                                                                                                                                                                                                                                                                                                              |             |             |              |      |
|                                              |                                                                            | buffer_calculatoin()             |                                                                                                                                                                                                                                                                                                              |             |             |              |      |
|                                              |                                                                            |                                  |                                                                                                                                                                                                                                                                                                              |             |             |              |      |
|                                              |                                                                            | power_weight_calculation()       |                                                                                                                                                                                                                                                                                                              |             |             |              |      |
+----------------------------------------------+----------------------------------------------------------------------------+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------------+--------------+------+
| Nuclear power, non-renewable plant proximity | World Resources Institute                                                  | File:                            | Similar distance weighted sum as Superfund site method                                                                                                                                                                                                                                                       | Devin       | X           | X            |      |
|                                              |                                                                            |                                  |                                                                                                                                                                                                                                                                                                              |             |             |              |      |
|                                              |                                                                            | global_power_plant_database.csv  |                                                                                                                                                                                                                                                                                                              |             |             |              |      |
|                                              |                                                                            |                                  |                                                                                                                                                                                                                                                                                                              |             |             |              |      |
|                                              |                                                                            | Fun:                             |                                                                                                                                                                                                                                                                                                              |             |             |              |      |
|                                              |                                                                            |                                  |                                                                                                                                                                                                                                                                                                              |             |             |              |      |
|                                              |                                                                            | buffer_calculation()             |                                                                                                                                                                                                                                                                                                              |             |             |              |      |
+----------------------------------------------+----------------------------------------------------------------------------+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------------+--------------+------+
| Hazardous waste facility proximity           |                                                                            |                                  | Similar distance weighted sum as Superfund site method                                                                                                                                                                                                                                                       | Devin       | X           |              |      |
+----------------------------------------------+----------------------------------------------------------------------------+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------------+--------------+------+
| Wastewater discharge indicator               | EJ Screen                                                                  |                                  | Estimated toxic chemical concentrations in stream segments within 500 meters of prison boundary, divided by distance in kilometers (km) in 2019                                                                                                                                                              | TBD         |             |              |      |
+----------------------------------------------+----------------------------------------------------------------------------+----------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+-------------+--------------+------+
