---
title: "Prison Value Analysis"
author: "Jackson Phippen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("setup.R")
library(mapview)
```

## Phase 1 Facilities
```{r}
#load in phase 1 data and phase 1 study prisons
phase1_data <- read.csv("outputs/final_df_2023-08-31.csv") %>% data.frame()
phase1_prisons <- read_sf("data/phase1/processed/prisons/study_prisons.shp")

#select only the indicators 
phase1_indicators <- phase1_data %>% select(
  flood_risk, 
  wildfire_risk,
  lst_avg,
  percent_tree_cover,
  mean_ozone, #will need to remove for new analysis (for now)
  avg_pm25,
  pesticides,
  trafficProx,
  npl_prox,
  rmp_prox,
  haz_prox
)

#let's see if there are any inf's here or other weird values 
#traffic, and rmp
summary(phase1_indicators)
```

```{r}
#let's generate some plots quickly of these infs. 
phase1_traffic_inf <- phase1_data %>% filter(trafficProx=="Inf")

flagged_site <- phase1_prisons %>% filter(FACILITYID%in%phase1_traffic_inf)

#load in traffic data
load("data/phase1/processed/traffic_proximity/aadt_2018.RData")

#step through calc traffic to identify road issue
#step through what calc traffic is doing. First add buffer
buffer <- st_buffer(flagged_site,500)

#find roads near this point
roads_nearby <- st_crop(aadt_2018,buffer) 

#quick plot
mapview(flagged_site)+
  mapview(roads_nearby)
```

```{r}
#next let's do rmp
phase1_rmp_inf <- phase1_data %>% filter(rmp_prox=="Inf")

flagged_site <- phase1_prisons %>% filter(FACILITYID%in%phase1_rmp_inf)

#load in rmp data
phase1_rmp_data <- read.csv("data/phase1/raw/EPA_RMP/EPA_Emergency_Response_(ER)_Risk_Management_Plan_(RMP)_Facilities.csv") %>% 
  st_as_sf(coords = c("LONGITUDE8", "LATITUDE83"), crs = 4269) %>%
  st_transform(crs = st_crs(flagged_site))

point <- st_is_within_distance(flagged_site,phase1_rmp_data,dist=5000)
#point (returns row 10690)

mapview(flagged_site)+
  mapview(phase1_rmp_data[10690,])
```

## Phase 2 Facilities
```{r}
#load in data and facilities
phase2_prisons <- read_sf("data/phase2/processed/prisons/study_prisons.gpkg")

#load in all current data (final df not yet ready)
phase2_haz_prox <- haz_prox <- read.csv("outputs/hazardous_waste_proximity_2026-02-12.csv") %>% 
  data.frame()

phase2_npl_prox <- read.csv("outputs/npl_proximity_2026-03-11.csv") %>% 
  data.frame()

phase2_pm25_prox <- read.csv("outputs/pm25_2026-03-26.csv") %>% 
  data.frame()

phase2_rmp_prox <- read.csv("outputs/rmp_proximity_2026-02-11.csv") %>% 
  data.frame()

phase2_wildfire_risk <- read.csv("outputs/wildfire_risk_2026-02-12.csv") %>% 
  data.frame()

#do a join just to have one sheet?
phase2_data_list <- list(phase2_haz_prox,
                    phase2_npl_prox,
                    phase2_pm25_prox,
                    phase2_rmp_prox,
                    phase2_wildfire_risk)
phase2_data <- purrr::reduce(phase2_data_list,left_join,by="FACILITYID")

#summary 
summary(phase2_data)
```
```{r}
#let's track down the infs in haz_prox 
#load in meta data
phase2_haz_data <- read.csv("data/phase2/processed/hazardous_waste/TSD_LQGs.csv") %>% 
  filter(!is.na(LONGITUDE83) | !is.na(LATITUDE83)) %>%
    st_as_sf(coords = c("LONGITUDE83", "LATITUDE83"), crs = 4269) %>%
    st_transform(crs = st_crs(phase2_prisons))

#pull flagged prisons
haz_inf <- phase2_data %>% filter(haz_prox=="Inf")
flagged_site <- phase2_prisons %>% filter(FACILITYID%in%haz_inf$FACILITYID)

#walk through calc_haz steps to determine features
dist <- 5000

prison_dist <- flagged_site %>%
  mutate(find_points = st_is_within_distance(., phase2_haz_data, dist = dist))

#plot to see overlap
mapview(flagged_site[1,])+
  mapview(haz_data[prison_dist[1,28],])

mapview(flagged_site[2,])+
  mapview(haz_data[prison_dist[2,28],])

mapview(flagged_site[3,])+
  mapview(haz_data[prison_dist[3,28],])

mapview(flagged_site[4,])+
  mapview(haz_data[prison_dist[4,28],])
```

```{r}
#next, let's do phase2_rmp
phase2_rmp_data <- read.csv("data/phase2/raw/RMP/EPA RMP Spreadsheets — The Data Liberation Project - Facilities.csv")%>%
    st_as_sf(coords = c("Lng", "Lat"), crs = 4269) %>%
    st_transform(crs = st_crs(phase2_prisons))

#flagged prisons
rmp_infs <- phase2_data %>% filter(rmp_prox=="Inf")
flagged_site <- phase2_prisons %>% filter(FACILITYID%in%rmp_infs$FACILITYID)

#find overlapping points
point <- st_is_within_distance(flagged_site,phase2_rmp_data,dist=5000)
#point returns 2343, 9495

mapview(flagged_site)+
  mapview(phase2_rmp_data[c(2353,9495),])
```

```{r}
#next, what I am curious about the prisons with large wildfire potential. 

#first map conus wildfire raster to understand what's up
phase2_wildfire_data <- rast("data/phase2/raw/wildfire_risk/Data/whp2023_GeoTIF/whp2023_cnt_conus.tif")

#mapview(phase2_wildfire_data) yeah, this broke, it was too big. 
#let's do this just by the largest prisons instead. 
wildfire_big <- phase2_data %>% filter(wildfire_risk>15000)
flagged_site <- phase2_prisons %>% filter(FACILITYID%in%wildfire_big$FACILITYID)

wildfire_site <- flagged_site %>%
      mutate(wildfire_risk = terra::extract(phase2_wildfire_data, flagged_site,fun = "mean", na.rm = TRUE)) %>%
      unnest(cols = wildfire_risk) %>%
      select(!ID) %>%
      rename("wildfire_risk" = names(flagged_site))

mapview(flagged_site[1,])+
  mapview(wildfire_site[1,]) #yeah, that was insightful.
```

